---
title: "Final Makk"
output: html_document
date: "2023-12-17"
---
```{r}
library(dplyr)
library(caret)
library(class)
library(e1071)
library(proxy)
library(Metrics)
```

```{r}
credit <- read.csv("~/Universidad/Analisis Multivariado/Final/credit_risk_dataset.csv")

selected_credit <- credit %>%
  select(loan_amnt, loan_percent_income, person_emp_length, loan_int_rate, loan_grade)
print(head(selected_credit))
```
```{r}
selected_credit[, 1:4] <- sapply(selected_credit[, 1:4], as.numeric)
selected_credit <- na.omit(selected_credit)
selected_credit$loan_grade <- as.factor(selected_credit$loan_grade)
```

```{r}
selected_cat <- c("A", "B", "C")
sample <- sample %>% filter(loan_grade %in% c('A', 'B', 'C'))

sample_size <- 350

set.seed(13)

sample <- sample_n(sample, size = sample_size)
```

```{r}
calculo_indicadores <- function(predicciones, etiquetas) {
  # Matriz de confusión
  matriz_confusion <- confusionMatrix(table(predicciones, etiquetas))
  
  # Accuracy
  accuracy <- matriz_confusion$overall["Accuracy"]
  
  # Precision
  precision <- matriz_confusion$byClass["Pos Pred Value"]
  
  # F1 Score
  f1 <- matriz_confusion$byClass["F1"]
  
  # Crear el objeto indicadores
  indicadores <- list("Matriz de confusion" = matriz_confusion$table,
                      "Accuracy" = accuracy,
                      "Precision" = precision,
                      "F1 Score" = f1)
  
  return(indicadores)
}
```

k Nearest Neighbor

Distnacias Euclideas
```{r}
X <- subset(sample, select = c('loan_amnt', 'loan_percent_income', 'person_emp_length', 'loan_int_rate'))
y <- sample$loan_grade

trainIndex <- createDataPartition(y, p = 0.8, list = FALSE)
X_train <- X[trainIndex, ]
X_test <- X[-trainIndex, ]
y_train <- y[trainIndex]
y_test <- y[-trainIndex]
```
```{r}
knn_model <- train(
  x = X_train,
  y = y_train,
  method = "knn",
  trControl = trainControl(method = "cv", number = 5),
  tuneGrid = param_grid
)
```


